name: Keep WS Awake

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping WS
        run: |
          echo "Pinging at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          curl -s "${{ secrets.WEBSOCKET_URL}}" || echo "Ignore 404 error"
